import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Triagem Web',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="mx-auto flex w-full max-w-[600px] flex-col justify-center gap-4 p-4">
          <span className="text-center text-sm text-gray-600">
            Made with 💙 by{' '}
            <a href="https://diegonatalo.vercel.app" className="underline">
              Diego Natalo
            </a>{' '}
            for my team
          </span>
          {children}

          <Toaster position="bottom-center" />
        </main>
      </body>
    </html>
  )
}
